[package]
name = "quick-pending"
version = "0.1.0"
edition = "2021"
license = "MIT"

[lib]
name = "quick_pending_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
rusqlite = { version = "0.40.2", features = ["bundled"] }
serde = { version = "1.0.229", features = ["derive"] }
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-autostart = "2.7.0"
tauri-plugin-global-shortcut = "2"
tauri-plugin-single-instance = "2.5.2"
